import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  console.log(__dirname, 'aaa')
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          CONGURATIONS!!!!
          {/* Welcome to <a href="https://nextjs.org">Next.js!</a> */}
        </h1>

        <p className={styles.description}>
         BUILDED SUCCESSFULY
        </p>

        <img src="https://wallpaperaccess.com/full/628286.jpg" alt="beautiful"  width="500"/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
